# Generated by Django 5.2.6 on 2025-09-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'Login 2FA'), ('RESET', 'Password reset'), ('PWD_CHANGE', 'Password change')], default='LOGIN', max_length=50),
        ),
    ]
