# Generated by Django 5.2.6 on 2025-09-04 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailotp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
